project_id = "dtzdqznjaynnrmnzaxzu"

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.check-low-stock]
verify_jwt = true

[functions.log-audit]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.change-user-email]
verify_jwt = true

[functions.send-payment-reminders]
verify_jwt = false

[functions.send-invoice-payment-notification]
verify_jwt = true

[functions.scheduled-backup]
verify_jwt = false
